import {
  FileArchive,
  FileAudio,
  FileCode2,
  FileJson,
  FileSpreadsheet,
  FileText,
  FileType,
  ImageIcon,
  Presentation,
  Video,
} from "lucide-react";

export const imageTypes = ["png", "jpg", "jpeg", "gif", "webp", "svg", "jfif"];
export const videoTypes = ["mp4", "webm", "ogg", "mov"];
export const audioTypes = ["mp3", "wav", "ogg"];
export const textTypes = ["txt", "md"];
export const codeTypes = [
  "js",
  "jsx",
  "ts",
  "tsx",
  "json",
  "html",
  "css",
  "py",
  "java",
  "cpp",
  "c",
  "rb",
  "php",
  "go",
  "rs",
  "swift",
  "kt",
  "sql",
  "sh",
  "bat",
  "pl",
  "r",
  "lua",
  "dart",
  "md",
];

export const officeTypes = [
  "doc",
  "docx",
  "docm",
  "dot",
  "dotx",
  "dotm",
  "xls",
  "xlsx",
  "xlsm",
  "xlsb",
  "xlt",
  "xltx",
  "xltm",
  "xlam",
  "ppt",
  "pptx",
  "pptm",
  "pot",
  "potx",
  "potm",
  "ppam",
  "pps",
  "ppsx",
  "ppsm",
  "sldx",
  "sldm",
];

export const EXT_ICON_MAP = {
  // images
  png: ImageIcon,
  jpg: ImageIcon,
  jpeg: ImageIcon,
  jfif: ImageIcon,
  gif: ImageIcon,
  webp: ImageIcon,
  svg: ImageIcon,
  bmp: ImageIcon,
  ico: ImageIcon,
  avif: ImageIcon,
  heic: ImageIcon,

  // video
  mp4: Video,
  webm: Video,
  mov: Video,
  avi: Video,
  mkv: Video,
  wmv: Video,
  flv: Video,
  m4v: Video,

  // audio
  mp3: FileAudio,
  wav: FileAudio,
  flac: FileAudio,
  aac: FileAudio,
  m4a: FileAudio,

  // text
  txt: FileText,

  // code / dev files
  js: FileCode2,
  jsx: FileCode2,
  ts: FileCode2,
  tsx: FileCode2,
  py: FileCode2,
  java: FileCode2,
  cpp: FileCode2,
  c: FileCode2,
  cs: FileCode2,
  rb: FileCode2,
  php: FileCode2,
  go: FileCode2,
  rs: FileCode2,
  swift: FileCode2,
  kt: FileCode2,
  sql: FileCode2,
  sh: FileCode2,
  bat: FileCode2,
  pl: FileCode2,
  r: FileCode2,
  lua: FileCode2,
  dart: FileCode2,
  html: FileCode2,
  css: FileCode2,
  scss: FileCode2,
  vue: FileCode2,
  yml: FileCode2,
  yaml: FileCode2,
  xml: FileCode2,

  // json
  json: FileJson,

  // spreadsheets
  csv: FileSpreadsheet,
  tsv: FileSpreadsheet,
  xls: FileSpreadsheet,
  xlsx: FileSpreadsheet,
  xlsm: FileSpreadsheet,
  xlsb: FileSpreadsheet,
  xlt: FileSpreadsheet,
  xltx: FileSpreadsheet,
  xltm: FileSpreadsheet,
  xlam: FileSpreadsheet,

  // archives
  zip: FileArchive,
  rar: FileArchive,
  "7z": FileArchive,
  tar: FileArchive,
  gz: FileArchive,

  // presentations (officeTypes ppt variants)
  ppt: Presentation,
  pptx: Presentation,
  pptm: Presentation,
  pot: Presentation,
  potx: Presentation,
  potm: Presentation,
  ppam: Presentation,
  pps: Presentation,
  ppsx: Presentation,
  ppsm: Presentation,
  sldx: Presentation,
  sldm: Presentation,

  // word documents
  doc: FileText,
  docx: FileText,
  docm: FileText,
  dot: FileText,
  dotx: FileText,
  dotm: FileText,

  // markdown / pdf
  md: FileText,
  pdf: FileType,
};

export const languageMap = {
  js: "javascript",
  jsx: "jsx",
  ts: "typescript",
  tsx: "tsx",
  json: "json",
  html: "markup",
  css: "css",
  py: "python",
  java: "java",
  cpp: "cpp",
  c: "c",
  rb: "ruby",
  php: "php",
  go: "go",
  rs: "rust",
  swift: "swift",
  kt: "kotlin",
  sql: "sql",
  sh: "bash",
  bat: "batch",
  pl: "perl",
  r: "r",
  lua: "lua",
  dart: "dart",
};
