import { useState } from "react";
import { createPortal } from "react-dom";
import { Card, CardHeader, CardTitle, CardDescription, CardContent, CardFooter } from "@/components/ui/card"; // Adjust imports based on your file structure
import { Button } from "@/components/ui/button";
import { X, Copy, Check, Eye, EyeOff, AlertTriangle, Download } from "lucide-react";

const NewlyGeneratedKeyDisplay = ({ credentials, setCredentials }) => {

    const [copiedKey, setCopiedKey] = useState({ rawApiKey: false, rawSsoSecret: false });
    const [showKey, setShowKey] = useState({ rawApiKey: false, rawSsoSecret: false });

    const formatKey = key => {
        return `••••••••••••••••••••••••••••••••••••••••${key.slice(-4)}`
    }

    if (!credentials) return null;

    const handleCopy = async (keyName) => {
        try {
            await navigator.clipboard.writeText(credentials[keyName]);
            setCopiedKey(prev => ({ ...prev, [keyName]: true }));
            setTimeout(() => setCopiedKey(prev => ({ ...prev, [keyName]: false })), 2000);
        } catch (err) {
            console.error("Failed to copy text: ", err);
        }
    };

    const handleShowHide = (keyName) => {
        setShowKey(prev => ({ ...prev, [keyName]: !prev[keyName] }));
    }

    const handleClose = () => {
        setCredentials(null);
    };

    const downloadEnvFile = () => {
        const envContent = `
# Generated by DocCentral
# Do not share this file. Keep it secure and private.

API_KEY=${credentials.rawApiKey}
SSO_SECRET=${credentials.rawSsoSecret}
        `.trim();

        const blob = new Blob([envContent], {
            type: "text/plain;charset=utf-8",
        });

        const url = window.URL.createObjectURL(blob);
        // console.log("🚀 ~ downloadEnvFile ~ url:", url)


        const link = document.createElement("a");
        link.href = url;
        link.download = "doccentral-credentials.env";

        document.body.appendChild(link);
        link.click();

        document.body.removeChild(link);
        window.URL.revokeObjectURL(url);
    };

    return createPortal(
        <div className="bg-zinc-950/40 flex fixed inset-0 justify-center items-center z-100 backdrop-blur">
            <Card className="w-130 overflow-hidden animate-in fade-in zoom-in-95 duration-150 border border-zinc-200 bg-white shadow-xl shadow-zinc-900/10 rounded-2xl p-0 gap-0">
                <div className="h-1 w-full bg-linear-to-r from-blue-500 via-blue-600 to-blue-500" />

                <div className="p-6 shadow-2xl flex flex-col gap-4 w-full">
                    <CardHeader className="p-0 flex justify-between items-start gap-1 border-b border-zinc-200 pb-3">
                        <div className="flex flex-col gap-1">
                            <CardTitle className="font-semibold text-lg leading-7 text-zinc-950">
                                API Key Generated Successfully
                            </CardTitle>
                            <CardDescription className="text-sm leading-5 text-zinc-500">
                                Make sure to copy your personal API key now. You won't be able to see it again.
                            </CardDescription>
                        </div>
                        <Button
                            variant="ghost"
                            size="icon"
                            className="cursor-pointer size-8 -mr-1 -mt-1 hover:bg-zinc-100 rounded-full"
                            onClick={handleClose}
                        >
                            <X className="size-4 text-zinc-500" />
                        </Button>
                    </CardHeader>

                    <CardContent className="flex p-0 flex-col gap-4 pt-2">
                        <div className="flex gap-3 rounded-lg bg-amber-50 p-3 text-amber-800 border border-amber-200/60">
                            <AlertTriangle className="size-5 shrink-0 text-amber-600 mt-0.5" />
                            <div className="text-xs leading-5 font-medium">
                                For security reasons, we cannot display this key to you again. If you lose it, you will need to revoke it and generate a new one.
                            </div>
                        </div>

                        <div className="flex flex-col gap-2">
                            <label className="flex font-semibold uppercase text-zinc-500 text-[11px] leading-4 tracking-[0.06em]">
                                API Key
                            </label>
                            <div className="relative flex items-center">
                                <div className="w-full font-mono text-sm bg-zinc-50 border border-zinc-200 rounded-lg pl-3 pr-28 py-2.5 text-zinc-900 focus:outline-hidden">
                                    {showKey.rawApiKey ? credentials.rawApiKey : formatKey(credentials.rawApiKey)}
                                </div>
                                <div className="absolute right-1.5 flex items-center gap-1">
                                    <Button
                                        type="button"
                                        variant="ghost"
                                        size="icon"
                                        className="cursor-pointer size-7 hover:bg-zinc-200/60 rounded-md text-zinc-500"
                                        onClick={() => handleShowHide("rawApiKey")}
                                        title={showKey.rawApiKey ? "Hide key" : "Show key"}
                                    >
                                        {showKey.rawApiKey ? <EyeOff className="size-4" /> : <Eye className="size-4" />}
                                    </Button>

                                    <Button
                                        type="button"
                                        variant="ghost"
                                        size="sm"
                                        className={`h-7 px-2.5 cursor-pointer rounded-md text-xs font-medium transition-all flex items-center gap-1.5 ${copiedKey.rawApiKey
                                            ? "bg-green-50 text-green-700 hover:bg-green-50"
                                            : "hover:bg-zinc-200/60 text-zinc-700"
                                            }`}
                                        onClick={() => handleCopy("rawApiKey")}
                                    >
                                        {copiedKey.rawApiKey
                                            ? <><Check className="size-3.5" />Copied</>
                                            : <><Copy className="size-3.5" />Copy</>
                                        }
                                    </Button>
                                </div>
                            </div>
                        </div>

                        <div className="flex flex-col gap-2">
                            <label className="flex font-semibold uppercase text-zinc-500 text-[11px] leading-4 tracking-[0.06em]">
                                SSO Secret
                            </label>
                            <div className="relative flex items-center">
                                <div className="w-full font-mono text-sm bg-zinc-50 border border-zinc-200 rounded-lg pl-3 pr-28 py-2.5 text-zinc-900 focus:outline-hidden break-all">
                                    {showKey.rawSsoSecret ? credentials.rawSsoSecret : formatKey(credentials.rawSsoSecret)}
                                </div>
                                <div className="absolute right-1.5 flex items-center gap-1">
                                    <Button
                                        type="button"
                                        variant="ghost"
                                        size="icon"
                                        className="cursor-pointer size-7 hover:bg-zinc-200/60 rounded-md text-zinc-500"
                                        onClick={() => handleShowHide("rawSsoSecret")}
                                        title={showKey.rawSsoSecret ? "Hide key" : "Show key"}
                                    >
                                        {showKey.rawSsoSecret ? <EyeOff className="size-4" /> : <Eye className="size-4" />}
                                    </Button>

                                    <Button
                                        type="button"
                                        variant="ghost"
                                        size="sm"
                                        className={`h-7 px-2.5 cursor-pointer rounded-md text-xs font-medium transition-all flex items-center gap-1.5 ${copiedKey.rawSsoSecret
                                            ? "bg-green-50 text-green-700 hover:bg-green-50"
                                            : "hover:bg-zinc-200/60 text-zinc-700"
                                            }`}
                                        onClick={() => handleCopy("rawSsoSecret")}
                                    >
                                        {copiedKey.rawSsoSecret
                                            ? <><Check className="size-3.5" />Copied</>
                                            : <><Copy className="size-3.5" />Copy</>
                                        }
                                    </Button>
                                </div>
                            </div>
                        </div>
                    </CardContent>

                    <CardFooter className="justify-end bg-white px-0 pb-0 pt-2">
                        <Button
                            className="cursor-pointer font-semibold bg-[#2b7fff] text-blue-50 hover:bg-blue-600 px-5 shadow-xs"
                            onClick={downloadEnvFile}
                        >
                            <Download className="size-4" />
                            Download Credentials
                        </Button>
                    </CardFooter>
                </div>
            </Card>
        </div>,
        document.body
    );
};

export default NewlyGeneratedKeyDisplay;